questionMatrix =[
    {estatus: "1", id_autor: "1",id_leccion: "2",id_pregunta: "10",
    orden: "1",patrona: "Factores bióticos",
    pregunta: "Comprende a todos los seres vivos de un ecosistema y las interrelaciones entre ellos",
    preguntaParte1: "Comprende a todos los seres vivos de un ecosistema y las interrelaciones entre ellos",
    preguntaParte2: "",
    respuesta2: "Fenómenos físicos",
    respuesta3: "Fenómenos químicos",
    respuesta4: "Factores bióticos",
    respuesta_correcta:"Lluvia", tipo:"1", tiene_imagen:"false"},

    {estatus: "1", id_autor: "1",id_leccion: "2",id_pregunta: "12",
    orden: "3", patrona: "ABIOTICOS",
    pregunta: "La humedad, la lluvia y la luz son ejemplos de factores:",
    preguntaParte1: "La humedad, la lluvia y la luz son ejemplos de factores:",
    preguntaParte2: "",
    respuesta2: null,
    respuesta3:null,
    respuesta4: "ABIOTICOS",
    respuesta_correcta: null,
    tipo: "2", tiene_imagen:"false"},
    
    {estatus:"1", id_autor:"1",id_leccion: "2"​​,id_pregunta: "13"​​,orden: "4"​​, patrona: "ABIOTICOS"​​,
    pregunta: "El mar, las rocas y el aire que se observan en la siguiente fotografía, son ejemplos de factores:"​​,
    preguntaParte1: "El mar, las rocas y el aire que se observan en la siguiente fotografía, son ejemplos de factores:"​​,
    preguntaParte2: ""​​,
    respuesta2: null​​,
    respuesta3: null​​,
    respuesta4: "ABIOTICOS"​​,
    respuesta_correcta: null​​,
    tipo: "2", tiene_imagen:"true"},

    {
    estatus: "1",
    id_autor: "1",
    id_leccion: "2",
    id_pregunta: "15",
    orden: "6",
    patrona: "Factores bióticos y abióticos",
    pregunta: "En la siguiente fotografía se observa un pato parado sobre la arena a punto de ser alcanzado por el agua de mar. Estos son ejemplos de:",
    preguntaParte1: "En la siguiente fotografía se observa un pato parado sobre la arena a punto de ser alcanzado por el agua de mar. Estos son ejemplos de:",
    preguntaParte2: "",
    respuesta2: "Factores bióticos y abióticos",
    respuesta3: "Factores abióticos",
    respuesta4: "Fenómenos físicos",
    respuesta_correcta: "Factores bióticos",
    tipo: "1", tiene_imagen:"true"}
];